project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://USERNAME.github.io # you must change this appropriately for RSS feeds to work properly
  title: "SITENAME"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/USERNAME
        
date-format: X
date: last-modified
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



